In [4]:
# lets learn about shape

import numpy as np

var = np.array([[1,2,3],[4,5,6]])

print(var)
print(var.shape)   # we have to use 'shape' for knowing the number of rows and columns

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
var2 = np.array( [1,2,3,4] , ndmin = 4 )

print(var2)
print( var.shape )   # it will return value as (1,1,1,4)     here 4 represents column and rest represents row because inside each [ ] there is only 1 row


[[[[1 2 3 4]]]]


In [11]:
# lets learn about reshape
x = np.array([1,2,3,4,5,6,7,8,9])
print( x )
print( x.ndim )

# lets convert it to multi dimension
y = x.reshape(3,3)  # reshape(x,y) where x is number of rows and y is number of columns 
print ( y )
print( y.ndim )

z = x.reshape(3,-1) # suppose the data is very big and u dont want to calculate the number of rows and columns so just enter the either row or column and the other value as -1
print( z )

[1 2 3 4 5 6 7 8 9]
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# lets learn about reshape for converting it to 3-D array
array = np.arange(16)
print( array )

array_dim = array.reshape( 4 , 2 , 2 )   # reshape( depth , rows , columns )  depth means how many total matrice of ( row X columns )
print( array_dim )

# now to convert it again to 1-D array we can pass -1 in the reshape()

array1 = array_dim.reshape( -1 )
print( array1 )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
