In [6]:
# lets learn about iteration in numpy

import numpy as np

arr = np.array ( np.arange(10) )
print(arr)
print(len(arr))
for i in arr:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
10
0
1
2
3
4
5
6
7
8
9


In [13]:
# iteration in 2 d

arr1 = np.array( [ np.random.randint(0,100,10) , np.random.randint(0,100,10) ])
print(arr1)
print()

# method of iteration for printing row completely
for i in arr1:    # this will acutally print row
    print(i)

print()
# method of iteration for printing the elements inside a row nd column

for x in arr1:
    for y in x:
        print(y)

[[28 31 42 89 57 41 67 30 70 80]
 [28 71 14 80 90 46 22 68 16 35]]

[28 31 42 89 57 41 67 30 70 80]
[28 71 14 80 90 46 22 68 16 35]

28
31
42
89
57
41
67
30
70
80
28
71
14
80
90
46
22
68
16
35


In [17]:
# lets learn it for 3 d array

arr2 = np.array ( [[ np.random.randint(0,100,8) , np.random.randint(0,100,8) ] , [ np.random.randint(0,100,8) , np.random.randint(0,100,8) ]] )

print(arr2)

for x in arr2:   # it will select the depth , in this case it will run two times due to depth is 2 in arr2
    for y in x:  # it will then select the rows , here total there are 2 rows in each depth 
        for z in y: # it will select the columns , here  
            print(z)
            

[[[88 85 87 70 13 85 14 81]
  [63 38 44 59 83 88 91 57]]

 [[18 79  4 53 34 81 89 38]
  [11 88 83 21 70  3 28 65]]]
88
85
87
70
13
85
14
81
63
38
44
59
83
88
91
57
18
79
4
53
34
81
89
38
11
88
83
21
70
3
28
65


In [20]:
arr3 = np.array ( [[ np.random.randint(0,100,8) , np.random.randint(0,100,8) ] , [ np.random.randint(0,100,8) , np.random.randint(0,100,8) ]] )

# we can also use the built in functions for printing elements
print(arr3)
print()

for i in np.nditer(arr3):
    print(i)


# if u also want to know the index then
for j,k in np.ndenumerate(arr3):
    print(j,k)
    

[[[39 91 48 57 23 54 57 63]
  [76 70 77 41  1 96 86  6]]

 [[72 18 96 25 72 14 36 20]
  [51 27 15 39 52 74 13 38]]]

39
91
48
57
23
54
57
63
76
70
77
41
1
96
86
6
72
18
96
25
72
14
36
20
51
27
15
39
52
74
13
38
(0, 0, 0) 39
(0, 0, 1) 91
(0, 0, 2) 48
(0, 0, 3) 57
(0, 0, 4) 23
(0, 0, 5) 54
(0, 0, 6) 57
(0, 0, 7) 63
(0, 1, 0) 76
(0, 1, 1) 70
(0, 1, 2) 77
(0, 1, 3) 41
(0, 1, 4) 1
(0, 1, 5) 96
(0, 1, 6) 86
(0, 1, 7) 6
(1, 0, 0) 72
(1, 0, 1) 18
(1, 0, 2) 96
(1, 0, 3) 25
(1, 0, 4) 72
(1, 0, 5) 14
(1, 0, 6) 36
(1, 0, 7) 20
(1, 1, 0) 51
(1, 1, 1) 27
(1, 1, 2) 15
(1, 1, 3) 39
(1, 1, 4) 52
(1, 1, 5) 74
(1, 1, 6) 13
(1, 1, 7) 38
