In [25]:
import numpy as np

rows = int(input('Enter the number of rows:'))
columns = int(input('Enter the number of columns:'))

data = np.array( np.random.randint( 0,100, (rows,columns)))

filename = 'numbers.txt'

np.savetxt( filename , data , delimiter = ',' , fmt= '%d')


Enter the number of rows: 3
Enter the number of columns: 10


In [26]:
a = np.loadtxt( 'numbers.txt' , delimiter = ',')
b = a.astype('int32')
print(b)
print()

[[88 72 85 24 14 58 36 80 83 30]
 [33 51 20 60 77 22 27 62 19 18]
 [97 14 47 53  7 67 61 14 81  1]]



In [31]:
# now lets use boolean

boolean = b > 50
print( boolean )
print()
for row in boolean :
    for column in row :
        if column == True:
            print(column)

[[ True  True  True False False  True False  True  True False]
 [False  True False  True  True False False  True False False]
 [ True False False  True False  True  True False  True False]]

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
