In [1]:
import numpy as np

arr = np.array ( np.random.randint(1,15,10) )
print( arr )
print()
# lets learn about where() function which will return the index of the elements if the condition is met
x = np.where( arr%2 == 0 )
print ( x )

[11 14  8  4  7  8 10  3  9  7]

(array([1, 2, 3, 5, 6]),)


In [3]:
# to learn how to sort an array

arr1 = np.array( np.random.randint(1,15,10) )
print( arr1 )
print()
arr1_sort = np.sort( arr1 )
print( arr1_sort )


# lets learn to place element in the array if the array is already sorted
# searchsorted() return the index

x = np.searchsorted( arr1_sort , [ 2,34 ,5,8 ] )  # we can pass the elements that we want to append as list also if we want to append more than 1 element
print()
print(x)
print()
print( arr1_sort )

[12 11  1  9  2  4  5 11 12 12]

[ 1  2  4  5  9 11 11 12 12 12]

[ 1 10  3  4]

[ 1  2  4  5  9 11 11 12 12 12]


In [30]:
# to sort 2 d array
arr2 = np.array( [ np.random.randint(1,15,10) , np.random.randint(1,15,10) , np.random.randint(1,15,10) ] )
print( arr2 )
print()

arr2_sort = np.sort( arr2 )    # it will sort the array in ascending order for each row
print( arr2_sort )

[[ 5  3  1 10  6  9  7 13  6  3]
 [ 1  5  1 13  8  1  6  5 10  5]
 [11  4  6  7  5  9 13 12  3  5]]

[[ 1  3  3  5  6  6  7  9 10 13]
 [ 1  1  1  5  5  5  6  8 10 13]
 [ 3  4  5  5  6  7  9 11 12 13]]
