In [8]:
# lets learn about zeros
import numpy as np
arr_zero=np.zeros(5)  # it will create array with 0 as value of each element and total 5 elements
print(arr_zero.ndim)
print(arr_zero)

# to create the zeros with 2 dim
arr_zero1 = np.zeros((3,5))        # (x,y) where x is row and y is column
print(arr_zero1)
print(arr_zero1.ndim)


1
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


In [12]:
# lets learn about ones
arr_ones = np.ones(5)
print(arr_ones)
print(arr_ones.ndim)

# to create ones with 2 dim array with x rows and y columns
x = 5
y = 10
arr_ones1 = np.ones((x,y))
print(arr_ones1)
print(arr_ones1.ndim)

[1. 1. 1. 1. 1.]
1
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
2


In [14]:
# lets learn about empty array
arr_em = np.empty(4)
print(arr_em)    # it will store some grabage value
print(arr_em.ndim)

# empty 2 dim array
arr_em1 = np.empty((3,4))
print(arr_em1)
print(arr_em1.ndim)

[0.00000000e+000 1.02066678e-311 1.02066678e-311 1.02066678e-311]
1
[[1.01962783e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.61590357e+184 7.48636201e-091 7.12309072e-067]
 [1.26125158e-076 7.46301170e-038 3.99910963e+252 1.46030983e-319]]
2


In [20]:
# lets learn about range function
arr = np.arange(10) # O/P : [0 1 2 3 4 5 6 7 8 9]
print(arr)

# some more refine way
arr1 = np.array( np.arange(10), ndmin=4 )
print( arr1,'\n',arr1.ndim )

[0 1 2 3 4 5 6 7 8 9]
[[[[0 1 2 3 4 5 6 7 8 9]]]] 
 4


In [23]:
# lets learn about identity matrix

arr_dia = np.eye(4) # it will create 4X4 matrix
print(arr_dia,'\n',arr_dia.ndim)        # it will have dimension as equal to 2 by-default

# we can also give input of rows and columns as well and it wil fill the rest elements as 0 and the diagonal element as 1
arr_dia1 = np.eye(3,5)  # 3 as row and 5 as column
print(arr_dia1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 2
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [24]:
# lets learn about linspace
arr_lin = np.linspace(0,15,6) # (first element, last element, number of elements) , it is same as Arithmatic Progression
print(arr_lin)

[ 0.  3.  6.  9. 12. 15.]
